<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-K903MU1U" ignored="0" name="t2" tests="3" failures="1" timestamp="2020-12-03T08:17:36 CST" time="0.043" errors="0">
  <testcase name="test01" time="0.008" classname="com.webtest.demo.Test02"/>
  <testcase name="test02" time="0.001" classname="com.webtest.demo.Test02">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.webtest.demo.Test02.test02(Test02.java:29)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test02 -->
  <testcase name="test03" time="0.001" classname="com.webtest.demo.Test02"/>
</testsuite> <!-- t2 -->
